// Design-system primitives. Import from one place:
//   import { Button, Modal, Input } from '@/components/ui'
export { Button, type ButtonProps, type ButtonVariant, type ButtonSize } from './Button'
export { IconButton, type IconButtonProps } from './IconButton'
export { Input, type InputProps } from './Input'
export { Textarea, type TextareaProps } from './Textarea'
export { Panel, type PanelProps } from './Panel'
export { Card, type CardProps } from './Card'
export { Modal, type ModalSize } from './Modal'
export { Tooltip, type TooltipPlacement } from './Tooltip'
export { Kbd } from './Kbd'
export { SegmentedControl, type SegmentOption } from './SegmentedControl'
export { Tabs, type TabItem } from './Tabs'
export { Toast } from './Toast'
export { ToastViewport } from './ToastViewport'
export { Section } from './Section'
export { Spinner } from './Spinner'
export { Slider, type SliderProps } from './Slider'
